# -*- coding: utf-8 -*-
"""NSFW_CLASSIFICATION.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VNJuKxi3m425fEu4oSOjI7qAcubj_2fR
"""

import numpy as np
from google.colab import drive
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.layers import Dropout, GlobalAveragePooling2D, Dense
from tensorflow.keras.applications import MobileNetV2, EfficientNetB7
from tensorflow.keras.models import Model, load_model
from sklearn.metrics import classification_report, confusion_matrix

!wget https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/extras/helper_functions.py

from helper_functions import unzip_data, plot_loss_curves

drive.mount('/content/drive')

unzip_data('/content/drive/MyDrive/nsfw_large_dataset_5_updated.zip')

dataset = '/content/nsfw_large_dataset_5_updated'

datagen = ImageDataGenerator(rescale=1/255.,
                             validation_split=0.2)

train_data = datagen.flow_from_directory(dataset,
                                         batch_size=32,
                                         target_size=(256,256),
                                         class_mode='categorical',
                                         subset='training',
                                         shuffle=True)

val_data = datagen.flow_from_directory(dataset,
                                       batch_size=32,
                                       target_size=(256,256),
                                       class_mode='categorical',
                                       subset='validation',
                                       shuffle=True)

final_model = load_model('MobileNetV2_nsfw_4_classes.keras')

# Load base model
base_model_1 = MobileNetV2(weights='imagenet', include_top=False, input_shape=(256, 256, 3))
base_model_1.trainable = False  # Freeze feature extractor

# Add custom classification head
x = base_model_1.output
x = GlobalAveragePooling2D()(x)
x = Dropout(0.3)(x)
x = Dense(128, activation='relu')(x)
output = Dense(5, activation='softmax')(x)  # For binary: NSFW vs SFW

new_model = Model(inputs=base_model_1.input, outputs=output)

new_model.compile(loss=tf.keras.losses.CategoricalCrossentropy(),
                  optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
                  metrics=['accuracy'])

history = new_model.fit(train_data,
                        epochs=35,
                        validation_data=(val_data))

new_model.save('nsfw_5_classes_final.keras')

plot_loss_curves(history=history)

import numpy as np

y_true = []
y_pred = []

for images, labels in val_data:
    preds = new_model.predict(images)
    preds = np.argmax(preds, axis=1)

    # Convert labels if needed
    if hasattr(labels, 'numpy'):
        labels = labels.numpy()

    # If labels are one-hot encoded
    if len(labels.shape) > 1 and labels.shape[1] > 1:
        labels = np.argmax(labels, axis=1)

    y_true.extend(labels)
    y_pred.extend(preds)


    if len(y_true) >= val_data.samples:
        break

y_true = np.array(y_true)
y_pred = np.array(y_pred)

print(classification_report(y_true, y_pred))

class_names = list(val_data.class_indices.keys())
print(class_names)

import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(8, 5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=class_names, yticklabels=class_names)
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix')
plt.show()

